name: verify-subs

on:
  pull_request:
    paths:
      - 'subs/**/*.srt'
      - 'scripts/**'
      - 'Makefile*'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Basic SRT sanity
        run: |
          set -e
          test -f subs/final_production.srt
          # index/timestamp の存在チェック（強制ではなく警告ベースに）
          if ! grep -Eq '^[0-9]+' subs/final_production.srt; then
            echo "⚠️  No numeric indices found (might still be acceptable)"
          fi
          if ! grep -Eq '[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3} --> ' subs/final_production.srt; then
            echo "❌ No valid timestamps"; exit 1
          fi
          echo "✅ Basic SRT format OK"